fig=figure('Name','Foarte inalta frecventa',...
            'Units','normalized',...
            'Position',[0.1 0.1 0.5 0.5],...
             'color', 'w',...
            'NumberTitle','off','color','w');


w=imread('fif.jpg');
image(w);
set(gca,'Position',[0 0 1 1]);


uicontrol('Style','pushbutton',...
             'Units','normalized',...
             'Position',[0.89 0.015 0.1 0.06],...
             'FontWeight','bold',...
             'FontSize',13,...
             'foregroundColor','white',...
             'backgroundcolor','#A2142F',...
             'String','Inapoi',...
             'Callback','start_int');
