function grafice(R,C,F,min,max)

fig=figure('Name','FTS',...
            'Units','normalized',...
            'Position',[0.1 0.1 0.8 0.8],...
             'color', 'w',...
            'NumberTitle','off','color','w');
set(gcf, 'Color','#4DBEEE');

w0=1/(R*C);
f0=1/(2*pi*R*C);
w = logspace(min,max,100);           %val omega
f = w./(2*pi);                       %val frecv
sus = 1j*w;
jos = w0 + 1j*w;
H = abs(sus./jos);                   %fct de transfer
gain = 20*log10(H);                  %calcul crestere
phase = 180/pi*(angle(sus./jos));    %calcul faza

subplot('Position',[0.49 0.55 0.5 0.23]);
semilogx(f, gain,'r','LineWidth',1.5);
grid on;
title('Caracteristica de frecventa la scara dublu logaritmica','fontname','Arial');
xlabel('Frecventa [Hz]','fontweight', 'bold', 'fontname', 'Arial','color','#A2142F','fontsize',10);
ylabel('Castigul [dB] ','fontweight', 'bold', 'fontname', 'Arial','color','#A2142F','fontsize',12);
subplot('Position',[0.49 0.1 0.5 0.23]);
semilogx(f,phase, 'c','LineWidth',1.5);
grid on;
title('Caracteristica de faza la scara semilogaritmica','fontname','Arial');
xlabel('Frecventa [Hz]','fontweight', 'bold', 'fontname', 'Arial','color','#A2142F','fontsize',10);
ylabel('Faza [°C]','fontweight', 'bold', 'fontname', 'Arial','color','#A2142F','fontsize',12);





RadioGroup1=uibuttongroup('Visible','on',...
                          'BackgroundColor','#A2142F',...
                          'ForegroundColor','white',...
                          'Title','Parametrii semnalului',...
                          'FontSize',19,...
                          'Position', [0.03 0.57 0.4 0.33],...
                          'FontWeight','Bold',...
                          'Fontname','Aharoni',...
                          'TitlePosition','centertop',...
                          'Tag','radiobutton'); 

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.1 0.8 0.37 0.2],...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'FontSize',16,...
          'FontWeight','bold',...
          'HorizontalAlignment','left',...
          'String','R [ ohm ] = ',...
          'Parent',RadioGroup1);

uicontrol('Style','edit',...
          'Units','normalized',...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'String',R,...
          'Position',[0.55 0.8 0.3 0.2],...
          'FontSize',16,...
          'FontWeight','bold',...
          'Parent',RadioGroup1,...
          'Callback', 'R=str2num(get(gco,''String'')),close,grafice(R,C,F,min,max)');

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.1 0.55 0.37 0.2],...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'FontSize',16,...
          'FontWeight','bold',...
          'HorizontalAlignment','left',...
          'String','F [ Hz ] = ',...
          'Parent',RadioGroup1);

uicontrol('Style','edit',...
          'Units','normalized',...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'String',F,...
          'Position',[0.55 0.55 0.3 0.2],...
          'FontSize',16,... 
          'FontWeight','bold',...
          'Parent',RadioGroup1,...    
          'Callback','F=str2num(get(gco,''String'')),close,grafice(R,C,A,F,N)');
     

         
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.85 0.02 0.1 0.06],...
          'string','Inapoi',...
          'FontName','Aharon',...
          'backgroundcolor','#80b2cb',...
          'foregroundcolor','white',...
          'FontSize',19,... 
          'FontWeight','Bold',...
          'Callback','pornire');       

