function interfata(R,C,F)
 
figure('Name','Filtru RC trece jos si sus',... 
       'Units','normalized',...
       'Position',[0.1 0.09 0.8 0.83],...
       'NumberTitle','off'); 
set(gcf, 'Color','#4DBEEE');

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.1 0.9 0.5 0.08],...
          'backgroundcolor','#A2142F',...',...
          'foregroundcolor','#ffffff',...
          'Fontname','Century',...
          'FontWeight','Bold',...
          'FontSize',30,...
          'String','Filtru RC trece jos si sus');


uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.4 0.8 0.5 0.05],...
          'backgroundcolor','#A2142F',...
          'foregroundcolor','white',...
          'FontWeight','Bold',...
          'Fontname','Aharoni',...
          'FontSize',18,...
          'String','Schema circuitului'); 


subplot('position',[0.47 0.45 0.4 0.3])
 z = imread('poza1.jpg');
 image(z); 
 axis off;

RadioGroup0=uibuttongroup('Visible','on',...
                          'BackgroundColor','#A2142F',...
                          'ForegroundColor','white',...
                          'Title','Parametrii circuitului',...
                          'FontSize',19,...
                          'Position',[0.1 0.3 0.25 0.3],...
                          'FontWeight','Bold',...
                          'Fontname','Aharoni',...
                          'TitlePosition','centertop',...
                          'Tag','radiobutton');


uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.1 0.75 0.35 0.15],...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'String','R [ Ω ] =',...
          'Fontsize', 16,...
          'FontWeight','bold',...
          'HorizontalAlignment','left',...
          'Parent',RadioGroup0);


uicontrol('Style','edit',...
          'Units','normalized',...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'Position',[0.47 0.75 0.36 0.15],...
          'String', R,...
          'Tag','rezistenta',...
          'Fontsize', 16,...
          'FontWeight','bold',...
          'Callback','R=str2num(get(gco,''string''));close;interfata(R,L,A,F,N)',...
          'Parent',RadioGroup0);


uicontrol('Style','text',...
          'Units','normalized',...
          'Position',[0.1 0.4 0.35 0.15],...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'String','C [ F ] =',...
          'Fontsize', 16,...
          'FontWeight','bold',...
          'HorizontalAlignment','left',...
          'Parent',RadioGroup0);


uicontrol('Style','edit',...
          'Units','normalized',...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'Position',[0.47 0.4 0.36 0.15],...
          'String', C,...
          'Tag','condensator',...
          'Fontsize', 16,...
          'FontWeight','bold',...
          'Callback','C=str2num(get(gco,''string''));close;interfata(R,C,A,F,N)',...
          'Parent',RadioGroup0);


 uicontrol('style','pushbutton',...
           'Units','normalized',...
           'Position',[0.52 0.35 0.3 0.06],...
           'String','FIF',...
           'FontName','Aharon',...
           'backgroundcolor','#A2142F',...
           'foregroundcolor','white',...
           'FontSize',19,... 
           'FontWeight','Bold',...
           'Callback','fif;');

w0=1/(R*C);
f0=1/(2*pi*R*C);

  uicontrol('Style','text',... 
            'Units','normalized',...
            'Position',[0.4 0.2 0.2 0.1],...
            'BackgroundColor','#4DBEEE',...
            'ForegroundColor','white',...
            'FontSize',16,...
            'FontWeight','bold',...
            'HorizontalAlignment','left',...
            'String','Frecventa de taiere ');

 uicontrol ('Style','text',... 
            'Units','normalized',...
            'Position',[0.4 0.1 0.2 0.1],...
            'BackgroundColor','#4DBEEE',...
            'ForegroundColor','white',...
            'FontSize',16,...
            'FontWeight','bold',...
            'HorizontalAlignment','left',...
            'String',[' f0 =',num2str(fix(f0)), ' Hz ']);


uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.72 0.2 0.2 0.1],...
          'BackgroundColor','#4DBEEE',...
          'ForegroundColor','white',...
          'FontSize',16,...
          'FontWeight','bold',...
          'HorizontalAlignment','left',...
          'String','Pulsatia ');


uicontrol ('Style','text',... 
            'Units','normalized',...
            'Position',[0.7 0.1 0.2 0.1],...
            'BackgroundColor','#4DBEEE',...
            'ForegroundColor','white',...
            'FontSize',16,...
            'FontWeight','bold',...
            'HorizontalAlignment','left',...
            'String',['w0= ',num2str(fix(w0)), ' rad/s ']);

             
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.85 0.02 0.1 0.06],...
          'string','Inapoi',...
          'FontName','Aharon',...
          'backgroundcolor','#A2142F',...
          'foregroundcolor','white',...
          'FontSize',19,... 
          'FontWeight','Bold',...
          'Callback','pornire');