function intrare(R,C,F)

figure('Name','Semnal de intrare si iesire',... 
 'Units','normalized',...
 'Position',[0.1 0.09 0.8 0.83],...
 'NumberTitle','off'); 
set(gcf, 'Color','#4DBEEE');

w = logspace(1, 5, 50);
f = w/(2 * pi);
T=1/f;
w0=1/(R*C);
f0=1/(2*pi*R*C);
t=0:T/100:N*T;
Vi=A*sin(2*pi*F*t);   
x=1i*w0*C;
y=R+1i*w0*C;
z=x/y;
Vo=z*Vi;

subplot('Position', [0.25 0.55 0.70 0.35]);
semilogx(fr,g,'r',f0,-3,'ob','LineWidth',2);
grid on;
xlabel('Frecventa,Hz');
ylabel('Castig, dB');

RadioGroup1=uibuttongroup('Visible','on',...
                          'BackgroundColor','#A2142F',...
                          'ForegroundColor','white',...
                          'Title','Parametrii semnalului',...
                          'FontSize',19,...
                          'Position', [0.6 0.4 0.25 0.3],...
                          'FontWeight','Bold',...
                          'Fontname','Aharoni',...
                          'TitlePosition','centertop',...
                          'Tag','radiobutton'); 

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.1 0.8 0.37 0.2],...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'FontSize',16,...
          'FontWeight','bold',...
          'HorizontalAlignment','left',...
          'String','A [ V ] = ',...
          'Parent',RadioGroup1);

uicontrol('Style','edit',...
          'Units','normalized',...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'String',A,...
          'Position',[0.55 0.8 0.3 0.2],...
          'FontSize',16,...
          'FontWeight','bold',...
          'Parent',RadioGroup1,...
          'Callback', 'A=str2num(get(gco,''String'')),close,grafice(R,C,A,F,N)');

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.1 0.55 0.37 0.2],...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'FontSize',16,...
          'FontWeight','bold',...
          'HorizontalAlignment','left',...
          'String','F [ Hz ] = ',...
          'Parent',RadioGroup1);

uicontrol('Style','edit',...
          'Units','normalized',...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'String',F,...
          'Position',[0.55 0.55 0.3 0.2],...
          'FontSize',16,... 
          'FontWeight','bold',...
          'Parent',RadioGroup1,...    
          'Callback','F=str2num(get(gco,''String'')),close,grafice(R,C,A,F,N)');

uicontrol('Style','text',... 
          'Units','normalized',...
          'Position',[0.1 0.3 0.37 0.2],...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'FontSize',16,...
          'FontWeight','bold',...
          'HorizontalAlignment','left',...
          'String','N = ', ...
          'Parent',RadioGroup1);

uicontrol('Style','edit',...
          'Units','normalized',...
          'BackgroundColor','white',...
          'ForegroundColor','black',...
          'String',N,...
          'Position',[0.55 0.3 0.3 0.2],...
          'FontSize',16,... 
          'FontWeight','bold',...
          'Parent',RadioGroup1,...    
          'Callback','N=str2num(get(gco,''String'')),close,grafice(R,C,A,F,N)');


subplot ('Position', [0.06 0.6 0.40 0.3]);
plot (t,Vi,'black');
grid on;
axis on;
title('Tensiunea de intrare[Vi]','FontSize',15,'Fontweight','b');
xlabel('t [ms]');
ylabel('A [V]');


subplot ('Position', [0.06 0.1 0.40 0.3]);
plot (t,Vo,'black');
grid on;
axis on;
title('Tensiunea de iesire[Vo]','FontSize',15,'Fontweight','b');
xlabel('t [ms]');
ylabel('A [V]');

         
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.85 0.02 0.1 0.06],...
          'string','Inapoi',...
          'FontName','Aharon',...
          'backgroundcolor','#80b2cb',...
          'foregroundcolor','white',...
          'FontSize',19,... 
          'FontWeight','Bold',...
          'Callback','pornire');      