close all;

Fig=figure('Name','Proiect Grafica',... 
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.7],...
           'NumberTitle','off');


        uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.3 0.8 0.4 0.1],...
        'foregroundcolor','white',...
        'Fontname','Century',...
        'Backgroundcolor', 'black',...
        'FontWeight','Bold',...
        'FontSize',25,...
        'String','Filtru RC trece jos si sus');


a=imread('poza2.jpg');
image(a);
set(gca,'position',[0.0 0.0 1.0 1.0]); 
   
      
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.1 0.5 0.2 0.1],...
          'string','Interfata',...
          'FontName','Aharoni',...
          'FontSize',15,...
          'Foregroundcolor','white',...
          'Backgroundcolor','black',...
          'FontWeight','Bold',...
          'Callback','start_int');
        

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.3 0.35 0.2 0.1],...
          'string','Grafice',...
          'FontName','Aharoni',...
          'FontSize',17,...
          'foregroundcolor','white',...
          'FontWeight','Bold',...
          'backgroundcolor','black',...
          'Callback','semnal');


uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.5 0.20 0.2 0.1],...
          'string','Prezentare',...
          'FontName','Aharoni',...
          'FontSize',17,...
          'foregroundcolor','white',...
          'FontWeight','Bold',...
          'backgroundcolor','black',...',..
          'Callback','open (''Prezentare.pptx'')');
         

uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.75 0.05 0.2 0.1],...
          'string','Inchide',...
          'FontName','Aharoni',...
          'FontSize',15,...   
          'foregroundcolor','white',...
          'backgroundcolor','black',...'
          'FontWeight','Bold',...
          'Callback','close;');  